application: pidouhui
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
  mime_type: image/x-icon

- url: /robots.txt
  static_files: images/robots.txt
  upload: images/robots.txt  

- url: /.*
  script: pidouhui.py

